import { IntlMessages } from "./intl";

export const messagesTr: IntlMessages = {
  "papereditor.title.background": "Arkaplan",
  "papereditor.title.preview-element": "Önizleme Elementi",
  "papereditor.title.layers": "Katmanlar",
  "papereditor.title.new-layer": "Yeni Katman",
  "papereditor.title.selected-layer": "Seçili Katman",
  "papereditor.title.selected-layers": "Seçili Katmanlar",
  "papereditor.title.layer-count": "$1 Seçili Katman",
  "papereditor.value.untitled-layer": "İsimsiz Katman",
  "papereditor.value.untitled-document": "İsimsiz Doküman",
  "papereditor.btn.delete-layer": "Katmanı Sil",
  "papereditor.btn.delete-selected-layers": "Seçili Katmanları Sil",
  "papereditor.btn.confirm-deletion": "Silme İşlemini Onayla",
  "papereditor.info.background":
    "Arkaplan katmanı, sadece düzenleme yaparken yol göstermesi amacıyla bulunmaktadır. Bu şablon ile baskı yaparken, arkaplan tamamen görmezden gelinecektir.",
  "papereditor.unit.inches": "İnç",
  "papereditor.unit.points": "Punto",
  "papereditor.unit.meters": "Metre",
  "papereditor.unit.centimeters": "Santimetre",
  "papereditor.unit.millimeters": "Milimetre",
  "papereditor.picker.loading": "Yükleniyor...",
  "papereditor.picker.no-image": "Mevcut görsel yok",
  "papereditor.picker.drag-drop-here": "Görsel dosyanızı sürükleyip bırakın",
  "papereditor.picker.or": "VEYA",
  "papereditor.picker.click-here": "Buraya Tıklayın",
  "papereditor.picker.upload-again": "Tekrar Yükle",
  "papereditor.picker.clear": "Temizle",
};
